databases:
<<<<<<< HEAD
  - name: explora_uchile_backend-postgres
    databaseName: explora_uchile_backend
    plan: free
    user: explora_uchile_backend

services:
  - type: redis
    name: explora_uchile_backend-redis
=======
  - name: {{project_name}}-postgres
    databaseName: {{project_name}}
    plan: free
    user: {{project_name}}

services:
  - type: redis
    name: {{project_name}}-redis
>>>>>>> 37cb4d29a35886fe431d5797246534db912e0cc2
    plan: free
    ipAllowList: [] # only allow internal connections

  - type: web
<<<<<<< HEAD
    name: explora_uchile_backend
    plan: free
    runtime: python
    buildCommand: "./render_build.sh"
    startCommand: "poetry run gunicorn explora_uchile_backend.wsgi:application --chdir backend --limit-request-line 8188 --log-file -"
=======
    name: {{project_name}}
    plan: free
    runtime: python
    buildCommand: "./render_build.sh"
    startCommand: "poetry run gunicorn {{project_name}}.wsgi:application --chdir backend --limit-request-line 8188 --log-file -"
>>>>>>> 37cb4d29a35886fe431d5797246534db912e0cc2
    envVars:
      - key: ENABLE_DJANGO_COLLECTSTATIC
        value: 1
      - key: AUTO_MIGRATE
        value: 1
      - key: DATABASE_URL
        fromDatabase:
<<<<<<< HEAD
          name: explora_uchile_backend-postgres
=======
          name: {{project_name}}-postgres
>>>>>>> 37cb4d29a35886fe431d5797246534db912e0cc2
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
<<<<<<< HEAD
          name: explora_uchile_backend-redis
=======
          name: {{project_name}}-redis
>>>>>>> 37cb4d29a35886fe431d5797246534db912e0cc2
          property: connectionString
      - fromGroup: python-services
      - fromGroup: integrations-credentials

  # As there aren't free plans for Workers in Render, the configuration for
  # celery workers/beat will be commented by default
  #
  # - type: worker
  #   name: worker-default
  #   runtime: python
  #   env: python
  #   buildCommand: poetry install
<<<<<<< HEAD
  #   startCommand: "poetry run celery --workdir backend --app=explora_uchile_backend worker --loglevel=info --max-memory-per-child=$WORKER_MAX_MEMORY  --concurrency=$WORKER_CONCURRENCY"
=======
  #   startCommand: "poetry run celery --workdir backend --app={{project_name}} worker --loglevel=info --max-memory-per-child=$WORKER_MAX_MEMORY  --concurrency=$WORKER_CONCURRENCY"
>>>>>>> 37cb4d29a35886fe431d5797246534db912e0cc2
  #   envVars:
  #     - key: REMAP_SIGTERM
  #       value: SIGQUIT
  #     - key: CELERY_BROKER_POOL_LIMIT
  #       value: 1
  #     - key: CELERY_BROKER_CONNECTION_TIMEOUT
  #       value: 30.0
  #     - key: CELERY_REDIS_MAX_CONNECTIONS
  #       value: null
  #     - key: CELERY_TASK_ACKS_ON_FAILURE_OR_TIMEOUT
  #       value: true
  #     - key: CELERY_TASK_REJECT_ON_WORKER_LOST
  #       value: false
  #     - key: CELERY_WORKER_PREFETCH_MULTIPLIER
  #       value: 1
  #     - key: CELERY_WORKER_CONCURRENCY
  #       value: null
  #     - key: CELERY_WORKER_MAX_TASKS_PER_CHILD
  #       value: 1000
  #     - key: CELERY_WORKER_SEND_TASK_EVENTS
  #       value: true
  #     - key: CELERY_EVENT_QUEUE_EXPIRES
  #       value: 60.0
  #     - key: CELERY_EVENT_QUEUE_TTL
  #       value: 5.0
  #     - key: WORKER_MAX_MEMORY
  #       sync: false
  #     - key: WORKER_CONCURRENCY
  #       sync: false
  #     - key: DATABASE_URL
  #       fromDatabase:
<<<<<<< HEAD
  #         name: explora_uchile_backend-postgres
=======
  #         name: {{project_name}}-postgres
>>>>>>> 37cb4d29a35886fe431d5797246534db912e0cc2
  #         property: connectionString
  #     - key: REDIS_URL
  #       fromService:
  #         type: redis
<<<<<<< HEAD
  #         name: explora_uchile_backend-redis
=======
  #         name: {{project_name}}-redis
>>>>>>> 37cb4d29a35886fe431d5797246534db912e0cc2
  #         property: connectionString
  #     - fromGroup: python-services
  #     - fromGroup: integrations-credentials
  # - type: worker
  #   name: beat
  #   runtime: python
  #   env: python
  #   buildCommand: poetry install
<<<<<<< HEAD
  #   startCommand: "poetry run celery --workdir backend --app=explora_uchile_backend beat --loglevel=info"
=======
  #   startCommand: "poetry run celery --workdir backend --app={{project_name}} beat --loglevel=info"
>>>>>>> 37cb4d29a35886fe431d5797246534db912e0cc2
  #   envVars:
  #     - key: REMAP_SIGTERM
  #       value: SIGQUIT
  #     - key: DATABASE_URL
  #       fromDatabase:
<<<<<<< HEAD
  #         name: explora_uchile_backend-postgres
=======
  #         name: {{project_name}}-postgres
>>>>>>> 37cb4d29a35886fe431d5797246534db912e0cc2
  #         property: connectionString
  #     - key: REDIS_URL
  #       fromService:
  #         type: redis
<<<<<<< HEAD
  #         name: explora_uchile_backend-redis
=======
  #         name: {{project_name}}-redis
>>>>>>> 37cb4d29a35886fe431d5797246534db912e0cc2
  #         property: connectionString
  #     - fromGroup: python-services
  #     - fromGroup: integrations-credentials

envVarGroups:
  - name: python-services
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: POETRY_VERSION
        value: 1.7.1
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
<<<<<<< HEAD
        value: explora_uchile_backend.settings.production
=======
        value: {{project_name}}.settings.production
>>>>>>> 37cb4d29a35886fe431d5797246534db912e0cc2
      - key: ALLOWED_HOSTS
        value: '*'
  - name: integrations-credentials
    envVars:
      - key: SENDGRID_USERNAME
        value: apikey
      - key: SENDGRID_PASSWORD
        value: placeholder-value
